### ISSUE TITLE
KCl nutrient output error

### ISSUE THREAD

**Issue by kisanjong** [kisanjong/rotalabutterfly#16]
KCl nutrient output. The ppm of K is correct but the ppm of Cl is not. This is directly the result of the original percentage value of the program. K and Cl should be near the same ppm, K slightly more; e.g. K=12.9ppm, Cl=11.7ppm (not 4.5ppm as the output).

**Comment by fablau** [comment]
Jason, do you think that's a problem in the compounds definition file or the calculations of the PHP backend?

**Comment by kisanjong** [comment]
I've not looked but I think the calculations, it may be worth checking the compounds file first, just  to check?

**Comment by fablau** [comment]
Yes, I see the following defined in the compounds for KCl:

KCl:
  K:      0.524447
  Cl:     0.18401
  tsp:    4500
  sol:    344
  target: K

I don't know any reference to compare the above data. Do you? Just to let you know, there's no custom calculation for KCl in the back-end, therefore I guess the problem is just in the compound definitions above.

**Comment by Audionut** [comment]
Zorfox from the plantedtank.net gave me these instructions.

"The reason I showed you this is that you can add any fertilizer you like if you know the composition of the molecule. You can get that by using a molar mass calculator (http://www.webqc.org/molecular-weight-of-KCl.html). If you enter KNO3 you'll see this

Symbol  Element Atomic weight   Atoms   Mass percent
K   Potassium   39.0983 1   38.6717 %
N   Nitrogen    14.0067 1   13.8539 %
O   Oxygen  15.9994 3   47.4745 %

Those are the same numbers listed in the ini file (move the decimal to the left two places though). NO3 is calculated off N. Otherwise, it's just the composition.

The sol (solubility), tsp (teaspoon weight) can both be set to 1 if you don't know them. Target needs to be one of the elements."

So the correct KCl values would be.

KCl:
K: 0.524448
Cl: 0.475552
tsp: 4500
sol: 344
target: K

**Comment by kisanjong** [comment]
Thanks audionut I'm just about to update this on rotalabutterfly.com so we can confirm its working before pushing it to github.

Great link :)

**Comment by kisanjong** [comment]
OK I've changed the compounds on rotalabutterfly.com and the result looks much the same as the K as it should.

Please test

**Comment by kisanjong** [comment]
Its Now confirmed by three users that the results are correct.

Thanks for your help :)

Issue closed!

**Comment by fablau** [comment]
Wonderful! Glad you sorted that out guys!!
